# -*- coding: utf-8 -*-
"""Martina_SAM2_Players.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1woTEuvvN45ugE4BxBG0BOxkbTjRIq9th

https://github.com/facebookresearch/sam2

## SAM2 **PEOPLE DETECTION** (to compare with YOLO)
"""

!git clone https://github.com/facebookresearch/sam2.git && cd sam2

!pip install -e .

!pip install -e ".[notebooks]"

!cd checkpoints && \
./download_ckpts.sh

using_colab = True

if using_colab:
    import torch
    import torchvision
    print("PyTorch version:", torch.__version__)
    print("Torchvision version:", torchvision.__version__)
    print("CUDA is available:", torch.cuda.is_available())
    import sys
    !{sys.executable} -m pip install opencv-python matplotlib
    !{sys.executable} -m pip install 'git+https://github.com/facebookresearch/sam2.git'

    !mkdir -p videos
    !wget -P videos https://dl.fbaipublicfiles.com/segment_anything_2/assets/bedroom.zip
    !unzip -d videos videos/bedroom.zip

    !mkdir -p ../checkpoints/
    !wget -P ../checkpoints/ https://dl.fbaipublicfiles.com/segment_anything_2/092824/sam2.1_hiera_large.pt

import os
# if using Apple MPS, fall back to CPU for unsupported ops
os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
import numpy as np
import torch
import matplotlib.pyplot as plt
from PIL import Image

# select the device for computation
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")
print(f"using device: {device}")

if device.type == "cuda":
    # use bfloat16 for the entire notebook
    torch.autocast("cuda", dtype=torch.bfloat16).__enter__()
    # turn on tfloat32 for Ampere GPUs (https://pytorch.org/docs/stable/notes/cuda.html#tensorfloat-32-tf32-on-ampere-devices)
    if torch.cuda.get_device_properties(0).major >= 8:
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True
elif device.type == "mps":
    print(
        "\nSupport for MPS devices is preliminary. SAM 2 is trained with CUDA and might "
        "give numerically different outputs and sometimes degraded performance on MPS. "
        "See e.g. https://github.com/pytorch/pytorch/issues/84936 for a discussion."
    )

from sam2.build_sam import build_sam2_video_predictor

sam2_checkpoint = "../checkpoints/sam2.1_hiera_large.pt"
model_cfg = "configs/sam2.1/sam2.1_hiera_l.yaml"

predictor = build_sam2_video_predictor(model_cfg, sam2_checkpoint, device=device)

def show_mask(mask, ax, obj_id=None, random_color=False):
    if random_color:
        color = np.concatenate([np.random.random(3), np.array([0.6])], axis=0)
    else:
        cmap = plt.get_cmap("tab10")
        cmap_idx = 0 if obj_id is None else obj_id
        color = np.array([*cmap(cmap_idx)[:3], 0.6])
    h, w = mask.shape[-2:]
    mask_image = mask.reshape(h, w, 1) * color.reshape(1, 1, -1)
    ax.imshow(mask_image)


def show_points(coords, labels, ax, marker_size=200):
    pos_points = coords[labels==1]
    neg_points = coords[labels==0]
    ax.scatter(pos_points[:, 0], pos_points[:, 1], color='green', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)
    ax.scatter(neg_points[:, 0], neg_points[:, 1], color='red', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)


def show_box(box, ax):
    x0, y0 = box[0], box[1]
    w, h = box[2] - box[0], box[3] - box[1]
    ax.add_patch(plt.Rectangle((x0, y0), w, h, edgecolor='green', facecolor=(0, 0, 0, 0), lw=2))

VIDEO_PATH = "/content/short_tennis_sample.mp4"
OUTPUT_PATH = "/content/SAM2_PLAYERS_tracking_short.mp4"

# extract JPEG frames from the video
# 1. Create the output directory first
!mkdir -p /content/shrunk_tennis_sample

# 2. Run the extraction command
!ffmpeg -i /content/short_tennis_sample.mp4 -q:v 2 -start_number 0 /content/shrunk_tennis_sample/%05d.jpg

# `video_dir` a directory of JPEG frames with filenames like `<frame_index>.jpg`
video_dir = "/content/shrunk_tennis_sample"
VIDEO_PATH = video_dir

# scan all the JPEG frame names in this directory
frame_names = [
    p for p in os.listdir(video_dir)
    if os.path.splitext(p)[-1] in [".jpg", ".jpeg", ".JPG", ".JPEG"]
]
frame_names.sort(key=lambda p: int(os.path.splitext(p)[0]))

# take a look the first video frame
frame_idx = 0
plt.figure(figsize=(9, 6))
plt.title(f"frame {frame_idx}")
plt.imshow(Image.open(os.path.join(video_dir, frame_names[frame_idx])))

inference_state = predictor.init_state(video_path=video_dir)

prompts = {}  # hold all the clicks we add for visualization

ann_frame_idx = 0  # the frame index we interact with
ann_obj_id = 2  # give a unique id to each object we interact with (it can be any integers)

# Let's add a positive click at (x, y) = (200, 300) to get started on the first object
points = np.array([[1070, 650]], dtype=np.float32)
# for labels, `1` means positive click and `0` means negative click
labels = np.array([1], np.int32)
prompts[ann_obj_id] = points, labels
_, out_obj_ids, out_mask_logits = predictor.add_new_points_or_box(
    inference_state=inference_state,
    frame_idx=ann_frame_idx,
    obj_id=ann_obj_id,
    points=points,
    labels=labels,
)

# show the results on the current (interacted) frame
plt.figure(figsize=(9, 6))
plt.title(f"frame {ann_frame_idx}")
plt.imshow(Image.open(os.path.join(video_dir, frame_names[ann_frame_idx])))
show_points(points, labels, plt.gca())
for i, out_obj_id in enumerate(out_obj_ids):
    show_points(*prompts[out_obj_id], plt.gca())
    show_mask((out_mask_logits[i] > 0.0).cpu().numpy(), plt.gca(), obj_id=out_obj_id)

ann_frame_idx = 0  # the frame index we interact with
ann_obj_id = 3  # give a unique id to each object we interact with (it can be any integers)

# Let's now move on to the second object we want to track (giving it object id `3`)
# with a positive click at (x, y) = (400, 150)
points = np.array([[700, 200]], dtype=np.float32)
# for labels, `1` means positive click and `0` means negative click
labels = np.array([1], np.int32)
prompts[ann_obj_id] = points, labels

# `add_new_points_or_box` returns masks for all objects added so far on this interacted frame
_, out_obj_ids, out_mask_logits = predictor.add_new_points_or_box(
    inference_state=inference_state,
    frame_idx=ann_frame_idx,
    obj_id=ann_obj_id,
    points=points,
    labels=labels,
)

# show the results on the current (interacted) frame on all objects
plt.figure(figsize=(9, 6))
plt.title(f"frame {ann_frame_idx}")
plt.imshow(Image.open(os.path.join(video_dir, frame_names[ann_frame_idx])))
show_points(points, labels, plt.gca())
for i, out_obj_id in enumerate(out_obj_ids):
    show_points(*prompts[out_obj_id], plt.gca())
    show_mask((out_mask_logits[i] > 0.0).cpu().numpy(), plt.gca(), obj_id=out_obj_id)

# run propagation throughout the video and collect the results in a dict
video_segments = {}  # video_segments contains the per-frame segmentation results
for out_frame_idx, out_obj_ids, out_mask_logits in predictor.propagate_in_video(inference_state):
    video_segments[out_frame_idx] = {
        out_obj_id: (out_mask_logits[i] > 0.0).cpu().numpy()
        for i, out_obj_id in enumerate(out_obj_ids)
    }

# render the segmentation results every few frames
vis_frame_stride = 30
plt.close("all")
for out_frame_idx in range(0, len(frame_names), vis_frame_stride):
    plt.figure(figsize=(6, 4))
    plt.title(f"frame {out_frame_idx}")
    plt.imshow(Image.open(os.path.join(video_dir, frame_names[out_frame_idx])))
    for out_obj_id, out_mask in video_segments[out_frame_idx].items():
        show_mask(out_mask, plt.gca(), obj_id=out_obj_id)

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

# --- CONFIG ---
OUTPUT_PATH = OUTPUT_PATH                            # previously defined
ALPHA = 0.45                                         # mask transparency
DEFAULT_FPS = 30                                     # used if we can't read fps from source mp4

# Optional: if you still have the original mp4 path, set it here to recover fps
SOURCE_MP4_FOR_FPS = "/content/short_tennis_sample.mp4"

def get_fps(source_mp4_path: str | None, default_fps: int = 30) -> int:
    if not source_mp4_path or not os.path.exists(source_mp4_path):
        return default_fps
    cap = cv2.VideoCapture(source_mp4_path)
    fps = cap.get(cv2.CAP_PROP_FPS)
    cap.release()
    if fps is None or fps <= 1e-3 or np.isnan(fps):
        return default_fps
    return int(round(fps))

def color_for_obj_id(obj_id: int) -> np.ndarray:
    """Return BGR uint8 color for a given obj_id (stable across frames)."""
    cmap = plt.get_cmap("tab10")
    r, g, b, _ = cmap(obj_id % 10)
    return np.array([int(b*255), int(g*255), int(r*255)], dtype=np.uint8)  # BGR

def overlay_masks_bgr(frame_bgr: np.ndarray, masks_by_obj: dict[int, np.ndarray], alpha: float = 0.45) -> np.ndarray:
    """Overlay all masks on a BGR frame."""
    out = frame_bgr.copy()
    if not masks_by_obj:
        return out

    for obj_id, mask in masks_by_obj.items():
        # mask can be (H,W) or (1,H,W) depending on how it's stored
        if mask.ndim == 3:
            mask2d = mask.squeeze()
        else:
            mask2d = mask

        if mask2d.dtype != np.bool_:
            mask2d = mask2d.astype(bool)

        if not np.any(mask2d):
            continue

        color = color_for_obj_id(int(obj_id))

        # alpha blend only on masked pixels
        out[mask2d] = (out[mask2d].astype(np.float32) * (1 - alpha) + color.astype(np.float32) * alpha).astype(np.uint8)

    return out

# --- Prepare writer ---
first_frame_path = os.path.join(video_dir, frame_names[0])
first_bgr = cv2.imread(first_frame_path)
if first_bgr is None:
    raise RuntimeError(f"Could not read first frame at: {first_frame_path}")

H, W = first_bgr.shape[:2]
fps = get_fps(SOURCE_MP4_FOR_FPS, DEFAULT_FPS)

fourcc = cv2.VideoWriter_fourcc(*"mp4v")
writer = cv2.VideoWriter(OUTPUT_PATH, fourcc, fps, (W, H))

# --- Render all frames ---
for frame_idx, fname in enumerate(frame_names):
    frame_path = os.path.join(video_dir, fname)
    frame_bgr = cv2.imread(frame_path)
    if frame_bgr is None:
        raise RuntimeError(f"Could not read frame {frame_idx} at: {frame_path}")

    masks_by_obj = video_segments.get(frame_idx, {})  # dict[obj_id] -> bool mask
    frame_bgr = overlay_masks_bgr(frame_bgr, masks_by_obj, alpha=ALPHA)

    writer.write(frame_bgr)

writer.release()
print("Saved:", OUTPUT_PATH)

# ============================================================
# Export video with a small black transparent box showing
# only the tracked players masks
# ============================================================
import os
import cv2
import numpy as np
from PIL import Image
from IPython.display import Video, display

# -----------------------------
# CONFIG
# -----------------------------
PLAYER_OBJ_IDS = None                 # e.g. [2, 3], or None = all tracked ids
MASK_PREVIEW_VIDEO_PATH = "/content/player_masks_preview_box.mp4"

# Box style
BOX_SCALE = 0.28                      # width of preview box relative to frame width
BOX_MARGIN = 24                       # distance from border
BOX_BG_ALPHA = 0.45                   # transparency of black box
BOX_BORDER_THICKNESS = 2
BOX_BORDER_COLOR = (180, 180, 180)    # light gray border

# Mask style inside the box
MASK_COLOR = (0, 0, 255)              # BGR red
MASK_ALPHA = 0.90                     # opacity of masks inside the box

# -----------------------------
# HELPERS
# -----------------------------
def get_fps(video_path, default_fps=30.0):
    fps = default_fps
    try:
        cap = cv2.VideoCapture(video_path)
        f = cap.get(cv2.CAP_PROP_FPS)
        cap.release()
        if f and f > 1 and not np.isnan(f):
            fps = float(f)
    except Exception:
        pass
    return fps

def to_mask_2d(mask, expected_hw=None):
    """
    Convert SAM2 mask to a clean 2D boolean mask.
    Supports shapes like:
    - (H, W)
    - (1, H, W)
    - occasionally other singleton-leading variants
    """
    mask = np.asarray(mask)

    # remove singleton dimensions safely
    mask = np.squeeze(mask)

    if mask.ndim != 2:
        raise ValueError(f"Mask could not be converted to 2D. Got shape: {mask.shape}")

    if expected_hw is not None and mask.shape != expected_hw:
        raise ValueError(f"Mask shape {mask.shape} does not match expected frame shape {expected_hw}")

    return mask.astype(bool)

# -----------------------------
# FRAME SIZE
# -----------------------------
first_img = np.array(Image.open(os.path.join(video_dir, frame_names[0])))
H, W = first_img.shape[:2]

fps = get_fps(VIDEO_PATH if "VIDEO_PATH" in globals() else None, default_fps=30.0)

# -----------------------------
# SELECT PLAYER IDS
# -----------------------------
if PLAYER_OBJ_IDS is None:
    ids = set()
    for fr in video_segments.values():
        ids.update(int(k) for k in fr.keys())
    PLAYER_OBJ_IDS = sorted(ids)

print("Using player obj ids:", PLAYER_OBJ_IDS)
print("Writing:", MASK_PREVIEW_VIDEO_PATH)

# -----------------------------
# PREVIEW BOX SIZE
# -----------------------------
box_w = int(W * BOX_SCALE)
box_h = int(box_w * H / W)   # keep same aspect ratio as full frame

x1 = BOX_MARGIN
y1 = BOX_MARGIN
x2 = x1 + box_w
y2 = y1 + box_h

# -----------------------------
# VIDEO WRITER
# -----------------------------
fourcc = cv2.VideoWriter_fourcc(*"mp4v")
out = cv2.VideoWriter(MASK_PREVIEW_VIDEO_PATH, fourcc, fps, (W, H))

# -----------------------------
# RENDER
# -----------------------------
for idx, fname in enumerate(frame_names):
    frame_path = os.path.join(video_dir, fname)
    frame_bgr = cv2.imread(frame_path)
    if frame_bgr is None:
        raise RuntimeError(f"Could not read frame {idx} at {frame_path}")

    fr = video_segments.get(idx, {})

    # union mask over selected player ids
    union_mask = np.zeros((H, W), dtype=bool)
    for oid in PLAYER_OBJ_IDS:
        if oid in fr:
            mask2d = to_mask_2d(fr[oid], expected_hw=(H, W))
            union_mask |= mask2d

    # create preview content: black background + red masks
    preview = np.zeros((H, W, 3), dtype=np.uint8)
    if union_mask.any():
        preview[union_mask] = MASK_COLOR

    # resize preview to box size
    preview_small = cv2.resize(preview, (box_w, box_h), interpolation=cv2.INTER_NEAREST)

    # draw semi-transparent black box on the original frame
    overlay = frame_bgr.copy()
    cv2.rectangle(overlay, (x1, y1), (x2, y2), (0, 0, 0), thickness=-1)
    frame_bgr = cv2.addWeighted(overlay, BOX_BG_ALPHA, frame_bgr, 1.0 - BOX_BG_ALPHA, 0)

    # blend the preview inside the box
    roi = frame_bgr[y1:y2, x1:x2].copy()
    mask_pixels = np.any(preview_small > 0, axis=2)

    if np.any(mask_pixels):
        roi[mask_pixels] = (
            roi[mask_pixels].astype(np.float32) * (1.0 - MASK_ALPHA)
            + preview_small[mask_pixels].astype(np.float32) * MASK_ALPHA
        ).astype(np.uint8)

    frame_bgr[y1:y2, x1:x2] = roi

    # optional border
    cv2.rectangle(frame_bgr, (x1, y1), (x2, y2), BOX_BORDER_COLOR, BOX_BORDER_THICKNESS)

    out.write(frame_bgr)

out.release()
print("✅ Done:", MASK_PREVIEW_VIDEO_PATH)
display(Video(MASK_PREVIEW_VIDEO_PATH, embed=True))

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

# --- CONFIG ---
OUTPUT_PATH = OUTPUT_PATH                            # previously defined
ALPHA = 0.45                                         # mask transparency
DEFAULT_FPS = 30                                     # used if we can't read fps from source mp4

# Optional: if you still have the original mp4 path, set it here to recover fps
SOURCE_MP4_FOR_FPS = "/content/short_tennis_sample.mp4"

def get_fps(source_mp4_path: str | None, default_fps: int = 30) -> int:
    if not source_mp4_path or not os.path.exists(source_mp4_path):
        return default_fps
    cap = cv2.VideoCapture(source_mp4_path)
    fps = cap.get(cv2.CAP_PROP_FPS)
    cap.release()
    if fps is None or fps <= 1e-3 or np.isnan(fps):
        return default_fps
    return int(round(fps))

def color_for_obj_id(obj_id: int) -> np.ndarray:
    """Return BGR uint8 color for a given obj_id (stable across frames)."""
    cmap = plt.get_cmap("tab10")
    r, g, b, _ = cmap(obj_id % 10)
    return np.array([int(b*255), int(g*255), int(r*255)], dtype=np.uint8)  # BGR

def overlay_masks_bgr(frame_bgr: np.ndarray, masks_by_obj: dict[int, np.ndarray], alpha: float = 0.45) -> np.ndarray:
    """Overlay all masks on a BGR frame."""
    out = frame_bgr.copy()
    if not masks_by_obj:
        return out

    for obj_id, mask in masks_by_obj.items():
        # mask can be (H,W) or (1,H,W) depending on how it's stored
        if mask.ndim == 3:
            mask2d = mask.squeeze()
        else:
            mask2d = mask

        if mask2d.dtype != np.bool_:
            mask2d = mask2d.astype(bool)

        if not np.any(mask2d):
            continue

        color = color_for_obj_id(int(obj_id))

        # alpha blend only on masked pixels
        out[mask2d] = (out[mask2d].astype(np.float32) * (1 - alpha) + color.astype(np.float32) * alpha).astype(np.uint8)

    return out

# --- Prepare writer ---
first_frame_path = os.path.join(video_dir, frame_names[0])
first_bgr = cv2.imread(first_frame_path)
if first_bgr is None:
    raise RuntimeError(f"Could not read first frame at: {first_frame_path}")

H, W = first_bgr.shape[:2]
fps = get_fps(SOURCE_MP4_FOR_FPS, DEFAULT_FPS)

fourcc = cv2.VideoWriter_fourcc(*"mp4v")
writer = cv2.VideoWriter(OUTPUT_PATH, fourcc, fps, (W, H))

# --- Render all frames ---
for frame_idx, fname in enumerate(frame_names):
    frame_path = os.path.join(video_dir, fname)
    frame_bgr = cv2.imread(frame_path)
    if frame_bgr is None:
        raise RuntimeError(f"Could not read frame {frame_idx} at: {frame_path}")

    masks_by_obj = video_segments.get(frame_idx, {})  # dict[obj_id] -> bool mask
    frame_bgr = overlay_masks_bgr(frame_bgr, masks_by_obj, alpha=ALPHA)

    writer.write(frame_bgr)

writer.release()
print("Saved:", OUTPUT_PATH)